DATA SEGMENT
   PORTA EQU 00H
   PORTB EQU 01H
   PORTC EQU 02H
   PORT_CON EQU 03H
DATA ENDS

CODE SEGMENT
 MOV AX,DATA
 MOV DS, AX

ORG 0000H 
START:
    MOV DX, PORT_CON
    MOV AL, 10010000B
    OUT DX,AL
    
    MOV AL, 00000000B
    MOV DX, PORTB
    OUT DX,AL
CHECK:
    MOV CL, 0
    MOV DL, 11111110B
L1 :    
    MOV DX, PORTC  
    MOV AL, 20H
    ADD AL, CL
    OUT DX,AL 
    
    MOV DX,PORTA
    IN AL,DX
      
    CMP AL, DL
    JNE RED
    ROL DL, 1
    INC CL
    CMP CL, 8
    JNE L1
       
GREEN:
    MOV AL, 00000010B
    MOV DX, PORTB
    OUT DX,AL
    JMP CHECK
RED:
    MOV AL, 00000001B
    MOV DX, PORTB
    OUT DX, AL
    JMP L1

CODE ENDS
END START